# Numpy 基础操作

## 初始化

In [1]:
import numpy as np

In [2]:
# 全1数组, 默认类型float64
a1 = np.ones(10)
print(a1)
print(a1.dtype)
print(np.issubdtype(a1.dtype, np.floating))

# 指定类型和形状shape
a11 = np.ones((3, 2), dtype=np.uint16)
print(a11)
print(a11.dtype)
print(np.issubdtype(a11.dtype, np.integer))


[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
float64
True
[[1 1]
 [1 1]
 [1 1]]
uint16
True


In [3]:
# 全0数组, 默认类型float64
a0 = np.zeros(10)
print(a0)
print(a0.dtype)
print(np.issubdtype(a0.dtype, np.floating))

# 全空数组，只分配空间不填值(垃圾值)
ae = np.empty((2, 4))
print(ae)
print(ae.dtype)
print(np.issubdtype(ae.dtype, np.floating))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
float64
True
[[ -0.00000000e+000  -1.73060412e-077   6.94698383e-310   6.94698383e-310]
 [  6.94698383e-310   6.44110685e-314   0.00000000e+000   5.56268465e-309]]
float64
True


In [4]:
# 创建类似数组,类型和形状相同
a12 = np.ones_like(a0)
print(a12)
a01 = np.zeros_like(a12)
print(a01)
ae1 = np.empty_like(a11)
print(ae1)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[    0     0]
 [    0 32768]
 [36052  8114]]


In [5]:
# 创建单位矩阵
eye1 = np.eye(4)
print(eye1)

eye11 = np.eye(5, dtype=np.integer)
print(eye11)

eye12 = np.identity(5, dtype=np.integer)
print(eye12)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [6]:
# 创建范围数组
ar1 = np.arange(16)
print(ar1)
# 重塑形状，生成新的数组
ar2 = ar1.reshape((4, 4))
print(ar2)

print(ar2 is ar1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
False


In [7]:
# 把输入数据转换为ndarray
ar3 = np.array(list('abcde'))
print(ar3)
ar4 = np.array(tuple('xyz'))
print(ar4)
ar5 = np.array(list(set('kksvvsv')))
print(ar5)
ar6 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]] )
print(ar6)

['a' 'b' 'c' 'd' 'e']
['x' 'y' 'z']
['s' 'k' 'v']
[[1 2 3 4]
 [5 6 7 8]]


In [8]:
# 随机数组
arx = np.random.randn(7, 4)
print(arx)

[[-0.5453849   1.04752532 -0.8268316   0.97650687]
 [-0.12644768  0.30499767 -0.33368384  1.22744571]
 [ 1.50511947  0.95579921 -0.28165937  0.56369648]
 [-2.06404614  0.05631185  1.63792676 -0.31888119]
 [ 0.47666446  0.42454422 -1.50741419 -0.72016695]
 [ 1.03480432 -0.89137233 -1.28205474  1.31176921]
 [ 2.08180072 -2.27185009 -0.90094373  0.45605662]]


In [9]:
# 元素重复操作
arr1 = np.arange(3)
print(arr1)
# 
arr2 = arr1.repeat(3)
print(arr2)

[0 1 2]
[0 0 0 1 1 1 2 2 2]


## 数组计算

In [10]:
ar7 = np.arange(1, 10).reshape((3,3))
print(ar7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# 求倒数
ar71 = 1 / ar7
print(ar71)

[[ 1.          0.5         0.33333333]
 [ 0.25        0.2         0.16666667]
 [ 0.14285714  0.125       0.11111111]]


In [12]:
# 数组相乘
ar72 = ar7 * ar7
print(ar72)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [13]:
# 数组相减
ar73 = ar7 - ar7
print(ar73)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
# 数组平方
ar74 = ar7 ** 2
print(ar74)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [15]:
# 数组平方根
ar75 = ar74 ** 0.5
print(ar75)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [16]:
# 数组四则运算
ar76 = (ar75 + 0.5) * 10
print(ar76)

[[ 15.  25.  35.]
 [ 45.  55.  65.]
 [ 75.  85.  95.]]


## 数组索引

In [17]:
print(ar76)
# 第一行
print(ar76[0])
# 指定坐标
print(ar76[0][0])
print(ar76[1, 1])
# 指定几行
print(ar76[1:3])
# 行列切片
print(ar76[1:3, 1:3])
# 只有冒号时，标识选择整个轴
print(ar76[:, -1:])
# 第一列
print(ar76[:, 0])

[[ 15.  25.  35.]
 [ 45.  55.  65.]
 [ 75.  85.  95.]]
[ 15.  25.  35.]
15.0
55.0
[[ 45.  55.  65.]
 [ 75.  85.  95.]]
[[ 55.  65.]
 [ 85.  95.]]
[[ 35.]
 [ 65.]
 [ 95.]]
[ 15.  45.  75.]


In [18]:
# 把指定列，设置为固定值，修改自身
ar77 = ar76.copy()
ar77[:, (0,2)] = 0
print(ar77)

[[  0.  25.   0.]
 [  0.  55.   0.]
 [  0.  85.   0.]]


## 数组转置和轴对换

In [19]:
print(ar7)
# 数组转置，行列切换（二维数组）,生成新数组
ar78 = ar7.T
print(ar78)
print(ar78 is ar7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
False


In [20]:
# 轴切换，三维以上
a9 = np.arange(16).reshape(2,2,4)
print(a9)
# 轴转置，生成新数组
a91 = a9.transpose((1, 0, 2))
print(a91)
print(a91 is a9)

# 轴对换，生成新数组
a92 = a9.swapaxes(1,2)
print(a92)
print(a92 is a9)

# 扁平化，多维变1维
a93 = a9.ravel()
print(a93)
a94 = a9.flatten()
print(a94)

# C顺序：行优先、F顺序：列优先。
a95 = a9.ravel('F')
print(a95)
a96 = a9.ravel('C')
print(a96)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
False
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
False
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  8  4 12  1  9  5 13  2 10  6 14  3 11  7 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## 双冒号操作

In [21]:
print(a96)
# 反转操作：生成新的数组
a97 = a96[::-1]
print(a97)

# 跳格操作：从第N个开始，每隔几个取一个
a98 = a97[1::2]
print(a98)

# 从0开始，间隔2
a99 = a97[::2]
print(a99)

# 从1开始，间隔3
a100 = a97[1::3]
print(a100)

# 从0开始，间隔3
a101 = a97[::3]
print(a101)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[14 12 10  8  6  4  2  0]
[15 13 11  9  7  5  3  1]
[14 11  8  5  2]
[15 12  9  6  3  0]
